"""Regenerate wiki/index.md from the wiki pages (design §6).

Usage: python scripts/wiki/generate_index.py [--wiki PATH]

Unconditionally rewrites <wiki>/index.md: one section per type in the §5
fixed order, entries sorted by `updated` descending (tie-break filename asc).
Writes ONLY wiki/index.md. Exit codes: 0 success, 1 scan error.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _common import TYPE_TO_FOLDER, coerce_date, iter_wiki_files  # noqa: E402

HEADER = (
    "<!-- AUTO-GENERATED by scripts/wiki/generate_index.py — do not edit. -->\n"
    "\n# Wiki index\n"
)


def build_index(wiki_root: Path) -> str:
    entries: dict[str, list[tuple[str, str, str, str]]] = {
        folder: [] for folder in TYPE_TO_FOLDER.values()
    }
    for relpath, folder, meta, _body in iter_wiki_files(wiki_root):
        if folder not in entries or meta is None:
            continue
        entry = {
            "relpath": relpath,
            "title": str(meta.get("title", "")),
            "summary": str(meta.get("summary_1line", "")),
            "updated": coerce_date(meta.get("updated")) or "0000-00-00",
            "confidence": str(meta.get("confidence", "")),
        }
        entries[folder].append(entry)

    lines = [HEADER]
    for folder in TYPE_TO_FOLDER.values():  # §5 fixed order
        if not entries[folder]:
            continue
        # Stable double sort: filename asc first, then updated desc on top,
        # yielding updated-descending with filename-ascending tie-break.
        page_list = sorted(entries[folder], key=lambda e: e["relpath"])
        page_list.sort(key=lambda e: e["updated"], reverse=True)
        lines.append(f"\n## {folder.capitalize()}\n")
        for entry in page_list:
            lines.append(
                f"- [{entry['title']}]({entry['relpath']}) — {entry['summary']} "
                f"(updated {entry['updated']}, confidence={entry['confidence']})"
            )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wiki", default="wiki", help="Wiki root directory")
    args = parser.parse_args(argv)

    wiki_root = Path(args.wiki)
    if not wiki_root.is_dir():
        print(f"[ERROR] wiki root not found: {wiki_root}", file=sys.stderr)
        return 1
    try:
        content = build_index(wiki_root)
        (wiki_root / "index.md").write_text(content, encoding="utf-8")
    except OSError as exc:
        print(f"[ERROR] scan/write failure: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
